package cn.com.demo.api.common;

import cn.com.demo.common.IMsgCode;

/**
 * Created by sunlong on 2014/11/4.
 */
public enum UserMessageCode implements IMsgCode {
    USER_GET_AUTHENTICATION_INFO_ERROR,
    USER_EXIST_ERROR,
    USER_NOT_EXIST_ERROR,
    USER_NAME_EXIST_ERROR,
    USER_EMAIL_EXIST_ERROR,
    USER_NEW_PASSWORD_BLANK_ERROR,
    USER_TWICE_PASSWORD_NOT_EQUAL_ERROR,
    USER_OLD_PASSWORD_ERROR,
    USER_PASSWORD_BLANK_ERROR,
    USER_NOT_LOGIN_ERROR,
    USER_ACCOUNT_INSUFFICIENT_ERROR,
    USER_PHONE_EXIST_ERROR,
    USER_TWICE_CODE_NOT_EQUAL_ERROR,
    USER_USERNAME_STOP_ERROR,
    USER_EXIST_BUT_ADD_ROLE,
    USER_USERNAME_EMAIL_PHONE_BLANK_ERROR,

    ROLE_EXIST_ERROR,
    ROLE_NOT_EXIST_ERROR,
    ROLE_ID_NOT_EXIST_ERROR,
    ROLE_DELETE_DEFAULT_ERROR,
    ROLE_UPDATE_DEFAULT_ROLE_NAME_ERROR,

    RESET_TOKEN_NOT_EXIST_ERROR,
    RESET_TOKEN_EXIST_ERROR,
    RESET_TOKEN_INVALID_ERROR,

    SUB_COUNT_LIMIT_ERROR
}
