package cn.com.demo.common;

/**
 * User: demo
 * Date: 13-4-15
 * Time: 下午3:01
 */
public enum CommonMessageCode implements IMsgCode{
    SERVER_ERROR,
    HEX_DECODE_EXCEPTION_ERROR,
    DATA_INTEGRITY_VIOLATION_EXCEPTION_ERROR,
    DB_MYBATIS_EXECUTE_ERROR,
    VALIDATION_ERROR,
    ACCESS_DENIED_ERROR,
    UNSUPPORTED_ENCODING_EXCEPTION_ERROR,

    FILE_WRITE_ERROR,

    QR_CODE_CREATE_ERROR,
    REMOTE_SERVICE_DOWN_ERROR,

    STUDENT_BUY_LESSON_NOT_ENOUGH_ERROR,

    USERNAME_OR_PASSWORD_ERROR,

    WEIXIN_RESPONSE_ERROR,
    WEIXIN_NOT_FOLLOW_PUBLIC_NUM_ERROR,
    FILE_POSTFIX_ERROR,
}
